FROM node:current

WORKDIR /app

#ENV LC_ALL C.UTF-8
#ENV LANG C.UTF-8

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm install

# COPY ./public/ /app/public
# COPY ./scripts /app/scripts
# COPY ./config /app/config
# COPY ./src/ /app/src
# COPY ./.env.development /app

EXPOSE 3000
CMD ["npm", "start"]
